os: windows

jobs:
  include:
    - stage: compile
      name: "Build gradle on windows"
      install:
        - export JAVA_HOME=${JAVA_HOME:-/c/jdk}
        - export PATH=${JAVA_HOME}/bin:${PATH}
        - choco install jdk8 -params 'installdir=c:\\jdk' -y
      script:
        - git status
        - java -version
        - ./gradlew --version
        - ./gradlew build --scan -s
